 - hosts: all
   tasks: 
     - package:
         name: "httpd"
         state: present
     - service:
         name: "httpd"
         state: started
     - copy:
          dest: "/var/www/html/index.html"
          content: "My First Ansible Task to configure webpage" 
